name: cards
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.4.0
  get: ^4.0.0-nullsafety.2
  get_storage: ^2.0.1
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  line_icons: ^2.0.1
  google_fonts: ^2.1.0
  octo_image: ^1.0.0+1
  cached_network_image: ^3.0.0
  vibration: ^1.7.4-nullsafety.0
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/data/Simple.json
    - assets/data/Standard.json
    - assets/data/AsBG.json
    - assets/icons/

